# ç«™ç‚¹åŸºæœ¬è®¾ç½®
theme: jekyll-theme-minimal
title: HuoMianLe's Blog
description: |
  Hi! ğŸ‘‹
  Welcome to my blog.
  This is my blog where I will share bits and pieces of programming, technology and life.

# ä½œè€…ä¿¡æ¯
#author:
  #name: HuoMianLe
  #email: your-email@example.com
  #github: your-github-username

# ç½‘ç«™è®¾ç½®
url: "https://huomianle.github.io"
#baseurl: ""
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

# ç¤¾äº¤åª’ä½“é“¾æ¥
social_links:
  github: HuoMianLe
  #twitter: your-twitter-handle
  #linkedin: your-linkedin-profile

# å¯¼èˆªèœå•
navigation:
  - title: é¦–é¡µ
    url: /
  - title: å…³äº
    url: /about/
  - title: æ–‡ç« 
    url: /posts/
  - title: é¡¹ç›®
    url: /projects/

# Google Analytics
#google_analytics: UA-XXXXXXXXX-X

# åˆ†é¡µè®¾ç½®
paginate: 5
paginate_path: "/page:num/"

# Disqusè¯„è®ºç³»ç»Ÿ
#disqus:
  #shortname: your-disqus-shortnam

# æ’ä»¶
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# æ’é™¤çš„æ–‡ä»¶å’Œæ–‡ä»¶å¤¹
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
