theme: jekyll-theme-primer

title: huomianle's Blog

description: >-
  ğŸ‘‹ Hello! Welcome to my blog. ğŸ‰
  I will continue to update my learning content. ğŸ‘Š

url: "https://huomianle.github.io"

permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

social_links:
  github: huomianle

#paginate: 5
#paginate_path: "/page:num/"


plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


#exclude:
  - .gitignore
