theme: jekyll-theme-cayman

title: huomianle's Blog

description: "ðŸ‘‹ Hello! Welcome to my blog. ðŸŽ‰<br><br>I will continue to update my learning content. ðŸ‘Š"

url: "https://huomianle.github.io"

permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

collections:
  leetcode:
    output: true
    permalink: /leetcode/:name/

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


#exclude:
  - .gitignore
