# ç«™ç‚¹åŸºæœ¬è®¾ç½®
theme: jekyll-theme-minimal
title: HuoMianLe's Blog
description: >-
  Hi! ğŸ‘‹
  Welcome to my blog.

# ä½œè€…ä¿¡æ¯
author:
  name: HuoMianLe
  #email: your-email@example.com
  github: HuoMianLe

# ç½‘ç«™è®¾ç½®
url: "https://huomianle.github.io"
baseurl: ""
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

# ç¤¾äº¤åª’ä½“é“¾æ¥
social_links:
  github: HuoMianLe
  #twitter: your-twitter-handle
  #linkedin: your-linkedin-profile

# å¯¼èˆªèœå•
#header_pages:
  #- about.md
  #- posts.md
  #- projects.md

# Google Analytics
#google_analytics: UA-XXXXXXXXX-X

# åˆ†é¡µè®¾ç½®
paginate: 5
paginate_path: "/page:num/"

# Disqusè¯„è®ºç³»ç»Ÿ
#disqus:
  #shortname: your-disqus-shortname

# æ’ä»¶
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# æ’é™¤çš„æ–‡ä»¶å’Œæ–‡ä»¶å¤¹
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
